---
apiVersion: v1
kind: Pod
metadata:
  name: test-demo
  labels:
    api: app
    env: dev
spec:
  container:
    - name: test-demo
      image: nginx
      ports:
        - containerPort: 8000
          protocol: TCP
          